# -*- coding: utf-8 -*-
"""Spamclassifier(gradio).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frywbkDFGM0ZI0OGXvx6tspPNOOn3vsv
"""

!pip install gradio scikit-learn pandas

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import gradio as gr

# Upload dataset
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv("spam.csv", encoding="latin-1")
df = df[['v1', 'v2']]
df.columns = ['label', 'message']
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

# Train model
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['message'])
y = df['label']

model = MultinomialNB()
model.fit(X, y)

# Prediction function
def classify_message(message):
    vec = vectorizer.transform([message])
    pred = model.predict(vec)[0]
    prob = model.predict_proba(vec)[0]

    if pred == 1:
        return f"🚨 Spam (Confidence: {max(prob)*100:.2f}%)"
    else:
        return f"✅ Not Spam (Confidence: {max(prob)*100:.2f}%)"

# Gradio UI
app = gr.Interface(
    fn=classify_message,
    inputs=gr.Textbox(lines=3, placeholder="Enter your message here..."),
    outputs="text",
    title="📧 Spam Classifier",
    description="Simple ML spam detection app"
)

app.launch()